### ISSUE TITLE
The 2FA repeats when trying to logging in admin panel

### ISSUE THREAD

**Issue by Michaelwucoc** [NodeBB/nodebb-plugin-2factor#92]
The 2FA screen will show again and again while trying to log in the admin panel.
I need to logout the account and relog in and get in the admin panel within 60 minutes..

**Comment by julianlam** [comment]
What version of NodeBB? I think this might've been an issue in older versions

**Comment by Michaelwucoc** [comment]
It's on 3.5.2

**Comment by Michaelwucoc** [comment]
It seem to solved after rebuild! Ty
